name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: download dependencies
        run: |
          go mod download

      - name: Install Python and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Unit-tests
        run: |
          go test -v -race -parallel 5 -shuffle=on -coverprofile=./cover.out -covermode=atomic ./...
  

      - name: Check coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out

      - name: Start app
        run: |
          go run cmd/web-server/main.go &
        env:
          CONFIG_PATH: "config/test.yaml"

      - name: integration-tests
        run: |
          go test -v -tags=integration ./...